var PLAYER=PLAYER||{};
PLAYER.Playlist=function(b,g,c,f,p,e,q,r,w,s){function h(b){console.log("youtube ready");"youtube"==c.videos[0].videoType&&(a.VIDEO.removeHTML5elements(),a.youtubePlayer.cueVideoById(a.videos_array[0].youtubeID),this.hasTouch||c.autoplay&&a.youtubePlayer.playVideo(),a.VIDEO.resizeAll())}function l(d){0===d.data&&c.playlist&&(a.videoid=parseInt(a.videoid)+1,a.videos_array.length==a.videoid&&(a.videoid=0),"Play next video"==c.onFinish?(a.element.find(".vp_itemSelected").removeClass("vp_itemSelected").addClass("vp_itemUnselected"),b(a.item_array[a.videoid]).removeClass("vp_itemUnselected").addClass("vp_itemSelected"),
"youtube"==c.videos[a.videoid].videoType?(a.ytWrapper.css({zIndex:501}),a.VIDEO.removeHTML5elements(),void 0!=a.youtubePlayer&&(a.youtubePlayer.cueVideoById(a.videos_array[a.videoid].youtubeID),a.youtubePlayer.setSize(f.width(),f.height()),this.hasTouch||a.youtubePlayer.playVideo())):"HTML5"==c.videos[a.videoid].videoType&&(a.ytWrapper.css({zIndex:0}),a.VIDEO.showHTML5elements(),void 0!=a.youtubePlayer&&(a.youtubePlayer.stopVideo(),a.youtubePlayer.clearVideo(),a.youtubePlayer.setSize(1,1)),e.canPlayType&&
e.canPlayType("video/mp4").replace(/no/,"")?(this.canPlay=!0,video_path=a.videos_array[a.videoid].video_path_mp4):e.canPlayType&&e.canPlayType("video/webm").replace(/no/,"")&&(this.canPlay=!0,video_path=a.videos_array[a.videoid].video_path_webm),a.VIDEO.resizeAll(),a.VIDEO.load(video_path,a.videoid),a.VIDEO.play(),b(a.element).find(".vp_infoTitle").html(a.videos_array[a.videoid].title),b(a.element).find(".vp_infoText").html(a.videos_array[a.videoid].info_text),b(a.element).find(".vp_nowPlayingText").html(a.videos_array[a.videoid].title))):
"Restart video"==c.onFinish&&void 0!=a.youtubePlayer&&(a.youtubePlayer.seekTo(0),a.youtubePlayer.playVideo()))}function t(b){a.vimeoStatus.text("paused")}function u(d){a.vimeoStatus.text("finished");c.playlist&&(a.videoid=parseInt(a.videoid)+1,a.videos_array.length==a.videoid&&(a.videoid=0),"Play next video"==c.onFinish?(a.element.find(".vp_itemSelected").removeClass("vp_itemSelected").addClass("vp_itemUnselected"),b(a.item_array[a.videoid]).removeClass("vp_itemUnselected").addClass("vp_itemSelected"),
"youtube"==c.videos[a.videoid].videoType?(a.preloader.stop().animate({opacity:0},0,function(){b(this).hide()}),a.vimeoWrapper.css({zIndex:0}),b("iframe#vimeo_video").attr("src",""),a.ytWrapper.css({zIndex:501}),a.VIDEO.removeHTML5elements(),void 0!=a.youtubePlayer&&(a.youtubePlayer.cueVideoById(a.videos_array[a.videoid].youtubeID),a.youtubePlayer.setSize(f.width(),f.height()),this.hasTouch||a.youtubePlayer.playVideo())):"HTML5"==c.videos[a.videoid].videoType?(a.preloader.stop().animate({opacity:0},
0,function(){b(this).hide()}),a.vimeoWrapper.css({zIndex:0}),b("iframe#vimeo_video").attr("src",""),a.ytWrapper.css({zIndex:0}),a.VIDEO.showHTML5elements(),void 0!=a.youtubePlayer&&(a.youtubePlayer.stopVideo(),a.youtubePlayer.clearVideo(),a.youtubePlayer.setSize(1,1)),e.canPlayType&&e.canPlayType("video/mp4").replace(/no/,"")?(this.canPlay=!0,video_path=a.videos_array[a.videoid].video_path_mp4):e.canPlayType&&e.canPlayType("video/webm").replace(/no/,"")&&(this.canPlay=!0,video_path=a.videos_array[a.videoid].video_path_webm),
a.VIDEO.resizeAll(),a.VIDEO.load(video_path,a.videoid),a.VIDEO.play(),b(a.element).find(".vp_infoTitle").html(a.videos_array[a.videoid].title),b(a.element).find(".vp_infoText").html(a.videos_array[a.videoid].info_text),b(a.element).find(".vp_nowPlayingText").html(a.videos_array[a.videoid].title)):"vimeo"==c.videos[a.videoid].videoType&&(b("iframe#vimeo_video").attr("src",""),a.preloader.stop().animate({opacity:0},700,function(){b(this).hide()}),a.hasTouch?document.getElementById("vimeo_video").src=
"http://player.vimeo.com/video/"+a.videos_array[a.vdeoid].vimeoID+"?autoplay=0?api=1&player_id=vimeo_video&color="+c.vimeoColor:document.getElementById("vimeo_video").src="http://player.vimeo.com/video/"+a.videos_array[a.vdeoid].vimeoID+"?autoplay=1?api=1&player_id=vimeo_video&color="+c.vimeoColor)):"Restart video"==c.onFinish&&a.vimeoPlayer.api("play"))}function v(b,c){a.vimeoStatus.text(b.seconds+"s played")}function n(){a.vimeoIframe=b("#vimeo_video")[0];a.vimeoPlayer=$f(a.vimeoIframe);a.vimeoStatus=
b(".status");a.vimeoPlayer.addEvent("ready",function(){console.log("vimeo ready");a.vimeoPlayer.addEvent("pause",t);a.vimeoPlayer.addEvent("finish",u);a.vimeoPlayer.addEvent("playProgress",v)})}console.log("PLAYLIST.js");var a=this;this.VIDEO=g;this.element=f;this.canPlay=q;this.CLICK_EV=r;this.hasTouch=s;this.preloader=p;this.options=c;this.videoid="VIDEOID";this.adStartTime="ADSTARTTIME";this.videoAdPlaying=!1;this.playlist=b("<div />");this.playlist.attr("id","vp_playlist");this.playlistContent=
b("<dl />");this.playlistContent.attr("id","vp_playlistContent");a.videos_array=[];a.item_array=[];this.ytWrapper=b("<div></div>");this.ytWrapper.attr("id","vp_ytWrapper");a.element&&a.element.append(a.ytWrapper);this.ytPlayer=b("<div></div>");this.ytPlayer.attr("id","vp_ytPlayer");this.ytWrapper.append(this.ytPlayer);this.vimeoWrapper=b("<div></div>");this.vimeoWrapper.attr("id","vp_vimeoWrapper");a.element&&a.element.append(a.vimeoWrapper);b("#vp_vimeoWrapper").html('<iframe id="vimeo_video" src="" width="100%" height="100%" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>');
var k=0;document.addEventListener("eventYoutubeReady",h,!1);var m=-1;b(c.videos).each(function(){m+=1;var d={id:m,title:this.title,videoType:this.videoType,youtubeID:this.youtubeID,vimeoID:this.vimeoID,video_path_mp4:this.mp4,video_path_webm:this.webm,description:this.description,thumbnail_image:this.thumbImg,info_text:this.info};a.videos_array.push(d);a.item=b("<div />");a.item.addClass("vp_item").css("top",String(k)+"px");a.item_array.push(a.item);a.item.addClass("vp_itemUnselected");var g='<div class="vp_itemRight"><div class="vp_title">'+
d.title+'</div><div class="vp_description"> '+d.description+"</div></div>";a.item.append('<div class="vp_itemLeft"><img class="vp_thumbnail_image" alt="" src="'+d.thumbnail_image+'"></img></div>');a.item.append(g);k+=64;a.playlistContent.append(a.item);a.item.bind(a.CLICK_EV,function(){a.scroll.moved||(a.preloader&&a.preloader.stop().animate({opacity:1},0,function(){b(this).show()}),a.videoid=d.id,a.VIDEO.resetPlayer(),"youtube"==c.videos[d.id].videoType?(a.preloader.stop().animate({opacity:0},0,
function(){b(this).hide()}),a.ytWrapper.css({zIndex:501}),a.VIDEO.removeHTML5elements(),a.vimeoWrapper.css({zIndex:0}),b("iframe#vimeo_video").attr("src",""),void 0!=a.youtubePlayer&&(a.youtubePlayer.setSize(f.width(),f.height()),"click"==a.CLICK_EV&&a.youtubePlayer.loadVideoById(a.videos_array[d.id].youtubeID),"touchend"==a.CLICK_EV&&a.youtubePlayer.cueVideoById(a.videos_array[d.id].youtubeID))):"HTML5"==c.videos[d.id].videoType&&(a.ytWrapper.css({zIndex:0}),a.vimeoWrapper.css({zIndex:0}),b("iframe#vimeo_video").attr("src",
""),a.VIDEO.showHTML5elements(),a.VIDEO.resizeAll(),void 0!=a.youtubePlayer&&(a.youtubePlayer.stopVideo(),a.youtubePlayer.clearVideo(),a.youtubePlayer.setSize(1,1)),e.canPlayType&&e.canPlayType("video/mp4").replace(/no/,"")?(this.canPlay=!0,a.video_path=d.video_path_mp4):e.canPlayType&&e.canPlayType("video/webm").replace(/no/,"")&&(this.canPlay=!0,a.video_path=d.video_path_webm),a.VIDEO.load(a.video_path,d.id),a.VIDEO.play(),b(a.element).find(".vp_infoTitle").html(d.title),b(a.element).find(".vp_infoText").html(d.info_text),
b(a.element).find(".vp_nowPlayingText").html(d.title),this.loaded=!1),"vimeo"==c.videos[d.id].videoType&&(a.preloader.stop().animate({opacity:0},700,function(){b(this).hide()}),a.vimeoWrapper.css({zIndex:501}),"click"==a.CLICK_EV&&(document.getElementById("vimeo_video").src="http://player.vimeo.com/video/"+a.videos_array[d.id].vimeoID+"?autoplay=1?api=1&player_id=vimeo_video&color="+c.vimeoColor),"touchend"==a.CLICK_EV&&(document.getElementById("vimeo_video").src="http://player.vimeo.com/video/"+
a.videos_array[d.id].vimeoID+"?autoplay=1?api=1&player_id=vimeo_video&color="+c.vimeoColor),a.VIDEO.removeHTML5elements(),a.ytWrapper.css({zIndex:0}),void 0!=a.youtubePlayer&&(a.youtubePlayer.stopVideo(),a.youtubePlayer.clearVideo(),a.youtubePlayer.setSize(1,1)),n()),a.element.find(".vp_itemSelected").removeClass("vp_itemSelected").addClass("vp_itemUnselected"),b(this).removeClass("vp_itemUnselected").addClass("vp_itemSelected"))});b(a.item_array[0]).removeClass("vp_itemUnselected").addClass("vp_itemSelected");
a.videoid=0;"youtube"==c.videos[0].videoType?(a.ytWrapper.css({zIndex:501}),a.vimeoWrapper.css({zIndex:0}),window.onYouTubePlayerAPIReady=function(){a.youtubePlayer=new YT.Player(document.getElementById("vp_ytPlayer"),{height:"1",width:"1",events:{onReady:h,onStateChange:l}})}):"HTML5"==c.videos[0].videoType?(a.ytWrapper.css({zIndex:0}),a.vimeoWrapper.css({zIndex:0}),window.onYouTubePlayerAPIReady=function(){a.youtubePlayer=new YT.Player(document.getElementById("vp_ytPlayer"),{height:"1",width:"1",
events:{onReady:h,onStateChange:l}})},e.canPlayType&&e.canPlayType("video/mp4").replace(/no/,"")?(this.canPlay=!0,a.video_path=a.videos_array[0].video_path_mp4):e.canPlayType&&e.canPlayType("video/webm").replace(/no/,"")&&(this.canPlay=!0,a.video_path=a.videos_array[0].video_path_webm),a.VIDEO.load(a.video_path,"0")):"vimeo"==c.videos[0].videoType&&(window.onYouTubePlayerAPIReady=function(){a.youtubePlayer=new YT.Player(document.getElementById("vp_ytPlayer"),{height:"1",width:"1",events:{onReady:h,
onStateChange:l}})},a.preloader.stop().animate({opacity:0},700,function(){b(this).hide()}),a.vimeoWrapper.css({zIndex:501}),a.hasTouch?document.getElementById("vimeo_video").src="http://player.vimeo.com/video/"+a.videos_array[0].vimeoID+"?autoplay=0?api=1&player_id=vimeo_video&color="+c.vimeoColor:c.autoplay?document.getElementById("vimeo_video").src="http://player.vimeo.com/video/"+a.videos_array[0].vimeoID+"?autoplay=1?api=1&player_id=vimeo_video&color="+c.vimeoColor:document.getElementById("vimeo_video").src=
"http://player.vimeo.com/video/"+a.videos_array[0].vimeoID+"?autoplay=0?api=1&player_id=vimeo_video&color="+c.vimeoColor,n())});a.playlistContent.css("height",String(k)+"px");a.totalWidth=c.videoPlayerWidth;a.totalHeight=c.videoPlayerHeight;c.playlist&&a.element&&(a.element.append(a.playlist),a.playlist.append(a.playlistContent));a.playerWidth=a.totalWidth-a.playlist.width();a.playerHeight=a.totalHeight-a.playlist.height();a.playlist.css({height:a.playerHeight,top:0});c.playlist&&(a.scroll=new iScroll(a.playlist[0],
{bounce:!1,scrollbarClass:"vp_myScrollbar"}));this.playlistW=this.playlist.width();this.playlistH=this.playlist.height()};
PLAYER.Playlist.prototype={hidePlaylist:function(){this.playlist.hide()},showPlaylist:function(){this.playlist.show()},resizePlaylist:function(b,g){this.playlist.css({left:b-this.playlist.width(),top:0,height:g})},playYoutube:function(b){void 0!=this.youtubePlayer&&(this.youtubePlayer.cueVideoById(this.videos_array[b].youtubeID),this.hasTouch||this.youtubePlayer.playVideo());this.VIDEO.resizeAll()},playVimeo:function(b){this.preloader.hide();this.vimeoWrapper.css({zIndex:501});this.hasTouch?document.getElementById("vimeo_video").src=
"http://player.vimeo.com/video/"+this.videos_array[b].vimeoID+"?autoplay=0?api=1&player_id=vimeo_video&color="+this.options.vimeoColor:document.getElementById("vimeo_video").src="http://player.vimeo.com/video/"+this.videos_array[b].vimeoID+"?autoplay=1?api=1&player_id=vimeo_video&color="+this.options.vimeoColor}};